version: "3.7"
services:
  app:
    environment:
        DISCORD_API_TOKEN: /run/secrets/token
    image: kfbi/budget-discord-nitro-api:latest
    ports:
      - "11337:1337"
    command: "/app/budgetDiscordNitro"

secrets:
    token:
        file: .token
